#!/bin/bash -e

# 引数の初期化
EP_FLAG=false
EP=""
MIC1="upamune"
MIC2="michiru_da"
MIC3=""
MIC4=""

PATH=~/.rye/shims:$PATH

# 引数を解析
while (( "$#" )); do
  case "$1" in
    --ep)
      EP_FLAG=true
      EP=$2
      shift 2
      ;;
    --MIC1|--mic1)
      MIC1=$2
      shift 2
      ;;
    --MIC2|--mic2)
      MIC2=$2
      shift 2
      ;;
    --MIC3|--mic3)
      MIC3=$2
      shift 2
      ;;
    --MIC4|--mic4)
      MIC4=$2
      shift 2
      ;;
    *)
      break
      ;;
  esac
done

# 引数のチェック
if [ "$#" -ne 1 ]; then
    echo "使用法: $0 [--ep EP] [--MIC1 名前] [--MIC2 名前] [--MIC3 名前] [--MIC4 名前] 音声ファイルが配置されているディレクトリ"
    exit 1
fi

# 引数がディレクトリかどうかをチェック
if [ ! -d "$1" ]; then
    echo "エラー: '$1' はディレクトリではありません。"
    exit 1
fi

# uvx コマンドがインストールされているかチェック
if ! command -v uvx &> /dev/null; then
    echo "エラー: 'uvx' コマンドがインストールされていません。"
    exit 1
fi

# Unixタイムスタンプを取得
unixtime=$(date +%s)

# 新しいディレクトリを作成 (カレントディレクトリの下のoutputディレクトリ内)
output_dir="output/"
if [ "$EP_FLAG" = true ]; then
    output_dir+="ep${EP}_"
fi
output_dir+="$unixtime"
mkdir -p "$output_dir"

# ファイルを新しいディレクトリにコピーし、リネーム
cp "$1/MIC1.WAV" "$output_dir/${MIC1}.wav"
cp "$1/MIC2.WAV" "$output_dir/${MIC2}.wav"
[ -n "$MIC3" ] && cp "$1/MIC3.WAV" "$output_dir/${MIC3}.wav"
[ -n "$MIC4" ] && cp "$1/MIC4.WAV" "$output_dir/${MIC4}.wav"

# uvx コマンドを変数として定義
UVX_LUFS_NORMALIZER="uvx --from git+https://github.com/upamune/lufs-normalizer lufs-normalizer@bd46466"

# lufs-normalizer コマンドを実行し、正規化されたファイルを保存
$UVX_LUFS_NORMALIZER --output_file "$output_dir/${MIC1}_normalized.wav" "$output_dir/${MIC1}.wav"
$UVX_LUFS_NORMALIZER --output_file "$output_dir/${MIC2}_normalized.wav" "$output_dir/${MIC2}.wav"
[ -n "$MIC3" ] && $UVX_LUFS_NORMALIZER --output_file "$output_dir/${MIC3}_normalized.wav" "$output_dir/${MIC3}.wav"
[ -n "$MIC4" ] && $UVX_LUFS_NORMALIZER --output_file "$output_dir/${MIC4}_normalized.wav" "$output_dir/${MIC4}.wav"


echo "処理が完了しました。出力ディレクトリ: $output_dir"

